name: Test and Deploy Website to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
      - name: Run HTML validation
        uses: Cyb3r-Jak3/html5validator-action@v2.0.0
        with:
          root: .
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress ./website/**/*.html

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
