name: Deploy Website Branch to GitHub Pages

on:
  push:
    branches:
      - website

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website branch
        uses: actions/checkout@v4
        with:
          ref: website
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
